common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 6
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    90
    det_range:     450.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

# rgb_params:
#     extrinsic_RT: 
#             [0.0183431,     -0.999727,      0.0145029, 0,
#             0.0112924,      -0.0142973,     -0.999834, 0,
#             0.999768,       0.0185038,      0.0110271, 0,
#             0.0,            0.0 ,           0.0,       1.0]
#     intrinsic:
#             [1482.90766,    0.0,        963.9341,   0.0,
#             0.0,        1481.21769,     554.14955,  0.0,
#             0.0,        0.0,            1.0,        0.0]
#     distCoff:
#             [0.055808, -0.188869, 0.000826, 0.001517, 0.0000]

#to update
# camera_intrinsic:
#          [845.142955,    0.     ,  615.159851 ,
#          0.     , 845.755731,  511.310303,
#          0.     ,    0.     ,    1.     ]
#    camera_dist_coeffs: [-0.246718, 0.088567, -0.000586, 0.000101, 0.000000]  #k1, k2, p1, p2, k3 


#    camera_ext_R:
#          [0.00404423, -0.0188911 ,  0.999813   ,
#            -0.999845  ,  0.0170314 ,  0.00436616,
#           -0.0171107 , -0.999676  , -0.0188193]
# camera_ext_t: [ 0.11845709, -0.12049132,  0.02114541]

rgb_params:
    # extrinsic_RT: 
    #         [0.00404423, -0.0188911 ,  0.999813, 0,
    #         -0.999845  ,  0.0170314 ,  0.00436616, 0,
    #         -0.0171107 , -0.999676  , -0.0188193, 0,
    #         0.0,            0.0 ,           0.0,       1.0]
    extrinsic_RT: 
            [0.00404423,-0.999845  ,  -0.0171107, 0 ,
            -0.0188911  ,  0.0170314 , -0.999676, 0 ,
            0.999813 , 0.00436616  , -0.0188193, 0,
            0.0,            0.0 ,           0.0,       1.0]
    intrinsic:
            [845.142955,    0.     ,  615.159851,   0.0,
            0.     , 845.755731,  511.310303,  0.0,
            0.0,        0.0,            1.0,        0.0]
    distCoff:
            [-0.246718, 0.088567, -0.000586, 0.000101, 0.000000]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
